name: Generate Password

on:
  push:
    branches:
      - password-generator

jobs:
  generate_password:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.9'

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any dependencies, create a requirements.txt file

    - name: Run Python script
      run: |
        python - <<EOF
        import random
        import string as a

        def generate_pass():
            c = random.randint(5, 10)
            d = a.ascii_lowercase
            e = a.ascii_uppercase
            f = a.digits
            g = random.choice(d) + random.choice(e) + random.choice(f)
            h = ''.join(random.choices(d + e + f, k=c - 3))
            i = list(g + h)
            random.shuffle(i)
            j = ''.join(i)
            return j

        k = generate_pass()
        print(k)
        EOF
