name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number for the package'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          pip install setuptools wheel twine

      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel --version ${{ github.event.inputs.version_number }}

      - name: Publish to PyPI
        run: |
          python -m twine upload --skip-existing dist/*

        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PASSWORD }}
